### ISSUE TITLE
gedit buttons ugly on gtk+ 3.14

### ISSUE THREAD

**Issue by haarp** [shimmerproject/Albatross#8]
After upgrading to gtk+ 3.14, buttons in gedit 3.10 have started to look quite ugly in this theme:

http://i.imgur.com/17ZmwdD.png

**Comment by haarp** [comment]
Gnome's Archive Manager (file-roller) 3.10 is also affected

**Comment by satya164** [comment]
Albatross doesn't support GTK 3.14 and is no longer actively maintained. Pull requests are welcome.

**Comment by haarp** [comment]
Which shimmerproject themes are currently maintained?

**Comment by satya164** [comment]
@haarp Greybird and Numix.

**Comment by ochosi** [comment]
Fixed in commit https://github.com/shimmerproject/Albatross/commit/3cfc608873e3b889d29b95761ed2960e243c8100
