### ISSUE TITLE
xfce4-panel pulseaudio-plugin uses wrong background color

### ISSUE THREAD

**Issue by haarp** [shimmerproject/Albatross#9]
I know Albatross is currently unmaintained, but I want to file this bug regardless for completeness' sake

This panel plugin uses the wrong background color. See http://i.imgur.com/a2jQAwz.png

The plugin developer informed me that this was a theme problem: https://bugzilla.xfce.org/show_bug.cgi?id=11797

**Comment by ochosi** [comment]
Fixed in https://github.com/shimmerproject/Albatross/commit/c759a49fd09514b884cf41cb33bdd318a7b6f9c0

**Comment by xstable** [comment]
Same again on 0.2.4-2 (manjaro linux): Light background on dark Controllbar-Panel.
